@BookTracker.Api_HostAddress = http://localhost:5065

### Health Check
GET {{BookTracker.Api_HostAddress}}/health
Accept: application/json

###

### Detailed Health Check
GET {{BookTracker.Api_HostAddress}}/health/detailed
Accept: application/json

###

### Swagger Documentation
GET {{BookTracker.Api_HostAddress}}/swagger/v1/swagger.json
Accept: application/json

###

